### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by ashwinbhaskar** [siftrics/sight-clojure#2]
The code lacks tests (no tests, actually). Tests need to be added so that lot of regression bugs can be caught. And CI pipeline can be setup which comes free with github/travis ci for open source projects

**Comment by ashwinbhaskar** [comment]
@siftrics let me know if you are okay with this. I would like to pick this up.

**Comment by siftrics** [comment]
Certainly. We can coordinate to get an API key dedicated for the tests.

**Comment by ashwinbhaskar** [comment]
@siftrics can you add the expected responses of this call

```
 (clj-http.client/post
                   "https://siftrics.com/api/sight/"
                   {:headers            {"Authorization" (str "Basic " (:apikey client))}
                    :body               (json/write-str payload)
                    :content-type       :json
                    :socket-timeout     10000               ;; in milliseconds
                    :connection-timeout 10000               ;; in milliseconds
                    :accept             :json})
```

Or is there a way for me to test it out (maybe with a dummy api key). Because I want to write tests for success and failure scenarios. So need to know how the actual response looks like

**Comment by ashwinbhaskar** [comment]
@siftrics why is there a `(Thread/sleep 500)` in the `do-poll` function ?

**Comment by siftrics** [comment]
The sleep is because we don't want to be continuously firing GET requests at the polling endpoint. There needs to be some delay between each request. 500 milliseconds seemed like a good midpoint between not wasting too much time and not hitting the endpoint too hard, although 1000 milliseconds might make a bit more sense.

I am super busy. I'll get the dummy API key set up eventually.

**Comment by siftrics** [comment]
@ashwinbhaskar Hey, man. I want to let you know I haven't forgotten about this. I have a lot of other things to tend to besides tests. I estimate I'll get to this over the weekend, when business cools down a bit.

**Comment by ashwinbhaskar** [comment]
@siftrics sure, no worries:)

> The sleep is because we don't want to be continuously firing GET requests at the polling endpoint. There needs to be some delay between each request.

The GET request in the code is a synchronous one. It will wait for the response, process it before it makes the next call. So the network call latency and the response time of the server would anyway be around 500ms right?  If that's the case then the extra sleep of 500ms will only hamper the UX.

**Comment by siftrics** [comment]
#3 closes this

**Comment by siftrics** [comment]
#3 closes this
